def COLOR_MAP = [
    SUCCESS: 'good',
    UNSTABLE: 'yellow',
    FAILURE: 'danger'
]

pipeline {
    // where do we run the pipeline/which agent
    agent any
    tools {
        // which version of maven we use
        maven 'MAVEN3.9'
        // which version of jdk we use
        jdk 'JDK17'
    }

    environment {
        registryCredentials =  'ecr:eu-north-1:awscreds'
        imageName = '841162690953.dkr.ecr.eu-north-1.amazonaws.com/vprofileappimage'
        vprofileRegistry = 'https://841162690953.dkr.ecr.eu-north-1.amazonaws.com'
        cluster = "vprofile"
        service = "vprofileappsvc"
    }

    stages {
        stage("Fetch code from git") {
            steps {
                // mention the pulgin we want to use and params
                git branch: 'docker', url : 'https://github.com/vvduth/vprofile-project.git'
            }
        }
        

        // install dependencies and build the project
        stage("Build Project") {
            steps {
                // run maven command to build the project
                sh 'mvn clean install -DskipTests=true'
            }
            post {
                // if build is successful
                success {
                    echo 'Build completed successfully!'
                    // use archiveArtifacts to store the built war file as a build artifact
                    archiveArtifacts artifacts: 'target/*.war'
                }
                // if build fails
                failure {
                    echo 'Build failed. Please check the logs for details.'
                }
            }
        }
        // run unit tsest using maven
        stage("Run Unit Tests") {
            steps {
                // run maven command to run unit tests
                sh 'mvn test'
            }
        }

        stage('checkstyle analysis') {
            steps {
                // run maven command to perform checkstyle analysis
                // nmaven will download checkstyle plugin and run it against the codebase
                sh 'mvn checkstyle:checkstyle'
            }
        }

        stage("SonarQube Analysis") {
            environment {
                // find this in jenkins => tools
                scannerHome = tool 'sonar6.2'
            }
            steps {
                // the nae that you set in the sonarQube server configuration in jenkins
                withSonarQubeEnv('sonarserver') {
                    sh '''${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=vprofile \
                    -Dsonar.projectName=vprofile \
                    -Dsonar.projectVersion=1.0 \
                    -Dsonar.sources=src/ \
                    -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/ \
                    -Dsonar.junit.reportPaths=target/surefire-reports/ \
                    -Dsonar.jacoco.reportPaths=target/jacoco.exec \
                    -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml 

                    '''
                }
            }
        }

        stage("Quality Gate") {
            steps {
                // timeout for waiting for the analysis to be done
                timeout(time: 1, unit: 'HOURS') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage("Build Docker Image") {
            steps {
                script {
                    dockerImage = docker.build(imageName + ":$BUILD_NUMBER",
                    "./Docker-files/app/multistage/" )
                }
            }
        }
        stage("Upload app image") {
            steps {
                script {
                    docker.withRegistry(vprofileRegistry, registryCredentials) {
                        dockerImage.push("$BUILD_NUMBER")
                        dockerImage.push("latest")
                    }
                }
            }
        }

        stage("Deploy to ECS") {
            steps {
                withAWS(credentials: 'awscreds', region: 'eu-north-1') {
                    sh """
                        aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment
                    """
                }
            }
        }

        stage("Remove image from jenkins server") {
            steps {
                    sh 'docker rmi -f $(docker images -a -q)'
            }
        }
    }

    post {
        always {
            echo 'Slack notification would be sent here.'
            slackSend channel: '#devopscicd', 
                      color: COLOR_MAP[ currentBuild.currentResult ],
                      message: "*${currentBuild.currentResult}:* Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL}) - !"
        }
    }
}